services:
    security.form.registration:
        class: TestProject\SecurityBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: secutity_user_registration }

    security.registration.service:
        class: TestProject\SecurityBundle\Service\RegistrationService
        arguments: ['@doctrine.orm.entity_manager', '@security.password_encoder', '@request_stack']

    security.user_listener:
        class: TestProject\SecurityBundle\EventListener\UserListener
        arguments: ['@mailer.mailer']
        tags:
            - { name: doctrine.orm.entity_listener }

    security.requst_listener:
            class: TestProject\SecurityBundle\EventListener\RequestListener
            arguments: ['@security.referral_transition.service']
            tags:
                - { name: kernel.event_listener, event: kernel.request }

    security.referral_transition.service:
            class: TestProject\SecurityBundle\Service\ReferralTransitionService
            arguments: ['@doctrine.orm.entity_manager', '@request_stack']

